# pip install matplotlib
# pip install numpy

import matplotlib.pyplot as plt
import numpy as np

def is_prime(n):
    """Check if a number is a prime number."""
    if n <= 1:
        return False
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return False
    return True

# Generate numbers using the formula
numbers = range(1, 501)
formula_results = [n**2 - n + 41 for n in numbers]
primes = [is_prime(f) for f in formula_results]

# Prepare data for the pie chart
prime_count = primes.count(True)
non_prime_count = primes.count(False)
labels = 'Prime Numbers', 'Non-Prime Numbers'
sizes = [prime_count, non_prime_count]
colors = ['lightblue', 'lightgreen']
explode = (0.1, 0)  # explode the 1st slice for better visibility

# Plotting the pie chart for the ratio of prime to non-prime numbers
fig1, ax1 = plt.subplots()
ax1.pie(sizes, explode=explode, labels=labels, autopct='%1.1f%%',
        shadow=True, startangle=90, colors=colors)
ax1.axis('equal')
plt.title('Ratio of Prime to Non-Prime Numbers for f = n^2 - n + 41')

# Adding a histogram to show the distribution of generated numbers
fig2, ax2 = plt.subplots()
ax2.hist(formula_results, bins=20, color='skyblue')
ax2.set_title('Distribution of Numbers Generated by f = n^2 - n + 41')
ax2.set_xlabel('Number')
ax2.set_ylabel('Frequency')

# Plotting the generated numbers in a line plot
fig3, ax3 = plt.subplots()
ax3.plot(numbers, formula_results, marker='o', linestyle='-', color='royalblue')
ax3.set_title('Generated Numbers by f = n^2 - n + 41')
ax3.set_xlabel('n')
ax3.set_ylabel('Generated Number')
ax3.grid(True)

# Plotting the generated numbers on a logarithmic scale
fig4, ax4 = plt.subplots()
ax4.plot(numbers, formula_results, marker='o', linestyle='-', color='darkorange')
ax4.set_title('Generated Numbers by f = n^2 - n + 41 (Log Scale)')
ax4.set_xlabel('n')
ax4.set_ylabel('Generated Number (Log Scale)')
ax4.set_yscale('log')
ax4.grid(True)

plt.tight_layout()
plt.show()


def log_formula_results():
    for n in range(1, 101):
        result = n**2 - n + 41
        print(f"n = {n}: {result}")

# Call the function to log the results
# log_formula_results()
